server:
  port: 0

spring:
  application:
    name: users-ws

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1


  rabbitmq:
    host: localhost
    port: 25672
    username: admin
    password: admin
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#  datasource:
#    url: jdbc:h2:mem:testdb

eureka:
  client:
    service-url:
      defaultZone: http://test:test@localhost:8010/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

gateway:
  ip: 127.0.0.1

token:
  expiration_time: 86400000 #1days(milliseconds)
  secret: local_secret

#login:
#  url:
#    path: /users/login


logging:
  level:
    com.example.myappapiusers.client: DEBUG

feign:
  hystrix:
    enabled: true